project:
  type: website
  output-dir: docs

website:
  title: "금융데이터분석"
  navbar:
    background: '	#ffbf00'
    style: "docked"
    right:
      - about.qmd
      
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

