---
title: "02_회귀분석"
date: "2023/10/10"
author: "Sungil Park"
description: "2023-2학기 R로 하는 금융데이터분석"
---

```{r, include=FALSE}
rm(list=ls())
library(tidyverse)
library(knitr)
library(DT)
```

## 실습 데이터

실습 데이터는 2020\~2022년의 월별 대인 손해액이다.<br>월별 대인 손해액을 회귀분석 한다.

```{r, echo=FALSE}
data <- readxl::read_xlsx("contents/2. 예측수준의 결정.xlsx",sheet = 1)
datatable(data)
```

## 선형회귀모형

#### formula

$$ y = b_0 + b_1x$$

```{r}
model <- lm(market ~ t, data = data)
model %>% summary
```

$$b_0 = 5879738$$

$$b_1 = 84666$$

### 회귀식

$$y = 5879738 + 84666x$$

p-value 가 0.007902로 0.05보다 작으므로 유의하다고 볼 수 있다.

R-squared 값이 0.1898로 설명력이 낮다고 볼 수 있다.

## 시각화

```{r}
ggplot(data, aes(x=t, y=market)) +
  geom_point() +
  geom_smooth(method='lm', se=FALSE)+
  labs(title = "Linear Regression of market ~ t", subtitle = "y = 5879738 + 84466 * t")+
  theme_minimal()
```

## 예측

-   2023년의 월별손해액 예측

```{r}
linear_regression <- function(t) {
  y <- 5879738 + 84466 * t
  return(y)
}

pred_t <- c(37:48)
pred_yymm <- c("2023.01","2023.02","2023.03","2023.04","2023.05","2023.06","2023.07","2023.08","2023.09","2023.10","2023.11","2023.12")
pred_market <- linear_regression(pred_t)

data.frame(pred_t,pred_yymm,pred_market)
```
