---
title: "정리"
date: "2023/11/09"
author: "Sungil Park"
description: "2023-2학기 R로 하는 금융데이터분석"
---

```{r, include=FALSE}
rm(list=ls())
library(tidyverse)
library(knitr)
```

<h1>HI</h1>

```{r}
project_data <- read.csv("contents/프로젝트자료.csv")
data_bin <- readxl::read_xlsx("contents/2. 예측수준의 결정.xlsx",sheet = 2)
data_sim <- readxl::read_xlsx("contents/2. 예측수준의 결정.xlsx",sheet = 3)
```

```{r}
bindo <- c(nrow(filter(project_data,in1_los!=0))/nrow(project_data),
           nrow(filter(project_data,mul_los!=0))/nrow(project_data),
           nrow(filter(project_data,jas_los!=0))/nrow(project_data),
           nrow(filter(project_data,cha_los!=0))/nrow(project_data))

simdo <- c(sum(project_data$in1_los)/nrow(filter(project_data,in1_los!=0)),
            sum(project_data$mul_los)/nrow(filter(project_data,mul_los!=0)),
            sum(project_data$jas_los)/nrow(filter(project_data,jas_los!=0)),
            sum(project_data$cha_los)/nrow(filter(project_data,cha_los!=0)))
        
summary <- data.frame(bindo,simdo)
row.names(summary) <- c("대인", "대물", "자손", "자차")
summary <- summary %>% mutate(sunbo = bindo*simdo)
```

```{r}
kable(summary)
```

```{r}
in1_bin_mod <- lm(in1_bin ~ t + factor(quat), data = data_bin)
mul_bin_mod <- lm(mul_bin ~ t + factor(quat), data = data_bin)
jas_bin_mod <- lm(jas_bin ~ t + factor(quat), data = data_bin)
cha_bin_mod <- lm(cha_bin ~ t + factor(quat), data = data_bin)

in1_sim_mod <- lm(in1_sim ~ year, data = data_sim)
mul_sim_mod <- lm(mul_sim ~ year, data = data_sim)
jas_sim_mod <- lm(jas_sim ~ year, data = data_sim)
cha_sim_mod <- lm(cha_sim ~ t + factor(quat), data = data_sim)
```

```{r, include=FALSE}
in1bin <- c(in1_bin_mod$coefficients[1] +in1_bin_mod$coefficients[2]*29, 
  in1_bin_mod$coefficients[1] +in1_bin_mod$coefficients[2]*30 + in1_bin_mod$coefficients[3],
  in1_bin_mod$coefficients[1] +in1_bin_mod$coefficients[2]*31 + in1_bin_mod$coefficients[4],
  in1_bin_mod$coefficients[1] +in1_bin_mod$coefficients[2]*32 + in1_bin_mod$coefficients[5])

mulbin <- c(mul_bin_mod$coefficients[1] +mul_bin_mod$coefficients[2]*29,
  mul_bin_mod$coefficients[1] +mul_bin_mod$coefficients[2]*30 + mul_bin_mod$coefficients[3],
  mul_bin_mod$coefficients[1] +mul_bin_mod$coefficients[2]*31 + mul_bin_mod$coefficients[4],
  mul_bin_mod$coefficients[1] +mul_bin_mod$coefficients[2]*32 + mul_bin_mod$coefficients[5])

jasbin <- c(jas_bin_mod$coefficients[1] +jas_bin_mod$coefficients[2]*29,
  jas_bin_mod$coefficients[1] +jas_bin_mod$coefficients[2]*30 + jas_bin_mod$coefficients[3],
  jas_bin_mod$coefficients[1] +jas_bin_mod$coefficients[2]*31 + jas_bin_mod$coefficients[4],
  jas_bin_mod$coefficients[1] +jas_bin_mod$coefficients[2]*32 + jas_bin_mod$coefficients[5])

chabin <- c(cha_bin_mod$coefficients[1] +cha_bin_mod$coefficients[2]*29,
  cha_bin_mod$coefficients[1] +cha_bin_mod$coefficients[2]*30 + cha_bin_mod$coefficients[3],
  cha_bin_mod$coefficients[1] +cha_bin_mod$coefficients[2]*31 + cha_bin_mod$coefficients[4],
  cha_bin_mod$coefficients[1] +cha_bin_mod$coefficients[2]*32 + cha_bin_mod$coefficients[5])

in1sim <- c(in1_sim_mod$coefficients[1] +in1_sim_mod$coefficients[2]*2023, 
  in1_sim_mod$coefficients[1] +in1_sim_mod$coefficients[2]*2023,
  in1_sim_mod$coefficients[1] +in1_sim_mod$coefficients[2]*2023,
  in1_sim_mod$coefficients[1] +in1_sim_mod$coefficients[2]*2023)

mulsim <- c(mul_sim_mod$coefficients[1] +mul_sim_mod$coefficients[2]*2023,
  mul_sim_mod$coefficients[1] +mul_sim_mod$coefficients[2]*2023,
  mul_sim_mod$coefficients[1] +mul_sim_mod$coefficients[2]*2023,
  mul_sim_mod$coefficients[1] +mul_sim_mod$coefficients[2]*2023)

jassim <- c(jas_sim_mod$coefficients[1] +jas_sim_mod$coefficients[2]*2023,
  jas_sim_mod$coefficients[1] +jas_sim_mod$coefficients[2]*2023,
  jas_sim_mod$coefficients[1] +jas_sim_mod$coefficients[2]*2023,
  jas_sim_mod$coefficients[1] +jas_sim_mod$coefficients[2]*2023)

chasim <- c(cha_sim_mod$coefficients[1] +cha_sim_mod$coefficients[2]*29,
  cha_sim_mod$coefficients[1] +cha_sim_mod$coefficients[2]*30 + cha_sim_mod$coefficients[3],
  cha_sim_mod$coefficients[1] +cha_sim_mod$coefficients[2]*31 + cha_sim_mod$coefficients[4],
  cha_sim_mod$coefficients[1] +cha_sim_mod$coefficients[2]*32 + cha_sim_mod$coefficients[5])
```

```{r, include=FALSE}
data_2023 <- data.frame(t = seq(29,32),
                        year = rep(2023,4),
                        quat = seq(1,4),
                        in1_bin = in1bin,
                        mul_bin = mulbin,
                        jas_bin = jasbin,
                        cha_bin = chabin,
                        in1_sim = in1sim,
                        mul_sim = mulsim,
                        jas_sim = jassim,
                        cha_sim = chasim)

boryo <- data_2023 %>% 
  mutate(in1_sun = in1_bin * in1_sim,
         mul_sun = mul_bin * mul_sim,
         jas_sun = jas_bin * jas_sim,
         cha_sun = cha_bin * cha_sim) %>% 
  select(year,quat,in1_sun,mul_sun,jas_sun,cha_sun)

colnames(boryo) <- c("year","quat","대인 순보험료","대물 순보험료","자손 순보험료","자차 순보험료")

data_2023

boryo
```
