---
title: "ANOVA"
date: "2023/11/14"
author: "Sungil Park"
description: "2023-2학기 R로 하는 금융데이터분석"
---

```{r, include=FALSE}
rm(list=ls())
library(tidyverse)
library(knitr)
```

```{r, include=FALSE}
# 데이터프레임 생성
df <- data.frame(a = c(11, 12, 13), 
                 b = c(21, 22, 23),
                 c = c(31, 32, 33))

# 일원분산분석 수행
result <- aov(value ~ variable, data = reshape2::melt(df))
summary(result)
```

## 데이터

```{r}
project_data <- read.csv("contents/프로젝트자료.csv")

df <- project_data %>% 
  filter(cha_los!=0) %>% 
  mutate(GAI_COD = factor(GAI_COD),
         차종 = as.factor(ifelse(car_knd %in% c("1A","1E"), "소형",
                               ifelse(car_knd %in% c("1F","1G","1H"), "준중형",
                                      ifelse(car_knd %in% c("1L","1M","1N"), "중형",
                                             ifelse(car_knd %in% c("1P","29"), "대형","SUB/VAN"))))))
```


```{r, echo=FALSE}
DT::datatable(df)
```

##  가입년별 분산분석

```{r}
aov(cha_los ~ GAI_COD, data = df) %>% summary()
```

##  차종별 분산분석

```{r}
aov(cha_los ~ 차종, data = df) %>% summary()
```

-------------------------------------------------

```{r}
df %>% ggplot(aes(x = cha_los, color = 차종, fill = 차종))+
  geom_density(alpha = 0.3)+
  scale_x_continuous(limits = c(0,1000000))+
  theme_minimal()
```


```{r}
df %>% ggplot(aes(y = cha_los, color = 차종, fill = 차종))+
  geom_boxplot()+
  theme_minimal()+
  scale_y_continuous(limits = c(0,1000000))
```























