---
title: "_"
date: "2023/11/16"
author: "Sungil Park"
description: "2023-2학기 R로 하는 금융데이터분석"
---

```{r, include=FALSE}
rm(list=ls())
library(tidyverse)
library(knitr)
```

```{r}
project_data <- read.csv("contents/프로젝트자료.csv")

project_data <- project_data %>%  
  mutate(
    GAI_COD = factor(GAI_COD),
    차종 = as.factor(case_when(
      car_knd %in% c("1A", "1E") ~ "소형",
      car_knd %in% c("1F", "1G", "1H") ~ "준중형",
      car_knd %in% c("1L", "1M", "1N") ~ "중형",
      car_knd %in% c("1P", "29") ~ "대형",
      TRUE ~ "SUB/VAN")))
```

```{r}
myfunc_1 <- function(df,y) {
  in1_bin <- sum(df$in1_los != 0) / nrow(df)
  mul_bin <- sum(df$mul_los != 0) / nrow(df)
  jas_bin <- sum(df$jas_los != 0) / nrow(df)
  cha_bin <- sum(df$cha_los != 0) / nrow(df)

  in1_dep <- sum(df$in1_los) / sum(df$in1_los != 0)
  mul_dep <- sum(df$mul_los) / sum(df$mul_los != 0)
  jas_dep <- sum(df$jas_los) / sum(df$jas_los != 0)
  cha_dep <- sum(df$cha_los) / sum(df$cha_los != 0)
  
  in1_sun <- in1_bin*in1_dep
  mul_sun <- mul_bin*mul_dep
  jas_sun <- jas_bin*jas_dep
  cha_sun <- cha_bin*cha_dep
  
  result_df <- data.frame(value = c(in1_bin, mul_bin, jas_bin, cha_bin, in1_dep, mul_dep, jas_dep, cha_dep,in1_sun, mul_sun, jas_sun, cha_sun) %>% as.character())
  rownames(result_df) <- c("대인빈도","대물빈도","자손빈도","자차빈도","대인심도","대물심도","자손심도","자차심도","대인순보","대물순보","자손순보","자차순보")
  colnames(result_df) <- y
  return(result_df)
}
```

```{r}
d_2 <- cbind(
  myfunc_1(project_data %>% filter(PIB_SEX==1),"PIB_SEX_1"),
  myfunc_1(project_data %>% filter(PIB_SEX==2),"PIB_SEX_2"),
  myfunc_1(project_data %>% filter(GAI_COD==1),"GAI_COD_1"),
  myfunc_1(project_data %>% filter(GAI_COD==2),"GAI_COD_2"),
  myfunc_1(project_data %>% filter(GAI_COD==3),"GAI_COD_3"),
  myfunc_1(project_data %>% filter(GAI_COD==4),"GAI_COD_4"),
  myfunc_1(project_data %>% filter(GAI_COD==5),"GAI_COD_5"),
  myfunc_1(project_data %>% filter(GAI_COD==6),"GAI_COD_6"),
  myfunc_1(project_data %>% filter(GAI_COD==7),"GAI_COD_7"),
  myfunc_1(project_data %>% filter(GAI_COD==8),"GAI_COD_8"),
  myfunc_1(project_data %>% filter(차종=="소형"),"차종_소형"),
  myfunc_1(project_data %>% filter(차종=="중형"),"차종_중형"),
  myfunc_1(project_data %>% filter(차종=="준중형"),"차종_준중형"),
  myfunc_1(project_data %>% filter(차종=="대형"),"차종_대형"),
  myfunc_1(project_data %>% filter(차종=="SUB/VAN"),"차종_SUB/VAN")
  )
```

```{r, echo=FALSE}
DT::datatable(d_2)
```
